# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be68d7a0c8699954991c8f148a811d2e1da006aff2a090788053237b3f5314fb90923479b8948b3581dfbc15a5273aa51b2f4ee3573706871d5d292b5eae62b7

test:
  secret_key_base: 6d619698c10b896f55767e67496cdbc20bd7f1879fa060a2148eb1053c230f609886a63e1cda14d81ea5ae8ee40cc407a3484479aa0d8f14daa76371c1111def

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
